### ISSUE TITLE
Refactor to eliminate the need to invoke the function when requiring

### ISSUE THREAD

**Issue by paul-barry-kenzan** [kenzanlabs/pipeline-compile-less#10]
This isn't an ideal means of using this pipeline, and should be refactored similar to [pipeline-validate-js](https://github.com/kenzanlabs/pipeline-validate-js)

```javascript
var gulp = require('gulp');
var lessPipeline = require('pipeline-compile-less')(); // invoke parent method. Should be eliminated
// would like to see:
// var lessPipeline = require('pipeline-compile-less');


gulp.task('default', function() {
  return gulp
    .src(['src/**/*.less'])
    .pipe(lessPipeline.compileLESS()); // invoke action method
});
```

**Comment by obuckley-kenzan** [comment]
agreed and there is a top level issue in keystone just for this.
https://github.com/kenzanlabs/keystone/issues/7

Just a matter of timing and resourcing.  As it stands now, we are improving each pipeline as we do needed maintenance work dictated by usage in the field.
