### ISSUE TITLE
Ability to configure output directory for concatenated files, default to original directory for output if not concatenated.

### ISSUE THREAD

**Issue by benmcosker** [kenzanlabs/pipeline-compile-less#17]
@obuckley-kenzan / @paul-barry-kenzan 

In using this pipeline, I encountered an issue outputting the processed files.  

Without a `gulp.dest` pipe set, the processed files (CSS, MAP) will output to project root with the project as a filename. Actually, without a `gulp.dest`, no output occurs. so to make the output a default, whether for concatenated or not would seem to be the desirable behavior.

In use this pipeline should output to root as default, with an optional parameter to output concatenated files to a specified directory. This presumes that the files processed are being concatenated.  If the files are not being concatenated it makes more sense to process and output the files to the same directory.  I will follow up with a refactor, if approved,  that reconfigures the config passed through to use as a default the project root if concatenated, with an option to pass through a specified directory OR if not concatenated, just output the same filename to the same directory as a processed css file. If this use case is specified, no parameters should be necessary. The default should be concatenated and to the root directory.

It may be desirable as a baseline behavior (if the additional baggage of the concatenation behaviors specified above is too much) to just be able to pass an output directory (with root as the default) AND specify it as a `gulp.dest` so that css is generated without the need to specify a dest directory.  

Does this issue identify something outside the expected use cases for this pipeline?

**Comment by paul-barry-kenzan** [comment]
@benmcosker 
Thanks for identifying the issue. I do agree that concatenated files should require an output directory, with the root be default. I agree that by default, a simple compilation should output to the source directory.  And this is not clear in the README usage examples. 

Could you provide some example use cases here on how you'd expect to use this pipeline within a gulpfile? I'd like to get an understanding of your expectations before having you put effort into an update.

Thanks again.

**Comment by benmcosker** [comment]
I propose the pipeline config to be refactored, with this as the default:

`var config = {
  autoprefix: true,
  concatCSS: true,
  outputFileName: handyman.getPackageName() + '.css',
  outputDirectory: './',
  addSourceMaps: true,
  plugins: {
    autoprefix: {browsers: ['last 2 versions']}
  }
};`

so, in the `gulpfile.js` if `.pipe(lessPipeline.compileLESS({concatCSS: false}))`, the filename processed will just process directly to the directory of the processed file. Passing the `outputDirectory` in the config will not effect output from the source directory. 

If `.pipe(lessPipeline.compileLESS({outputDirectory: './src/css' }))` is passed, the default root directory should be overwritten so `src/css` is specified and since no filename is specified the project name.css is used. This will take all  LESS files and concatenate them to one css file in the above directory. Not passing any parameters concatenates all the LESS to root in one CSS file.

**Comment by obuckley-kenzan** [comment]
@benmcosker / @paul-barry-kenzan 
While do agree on output directory, I'm not sure root should be default, per se.  I know for Kenzan, for built files, we've generally used `./dest/` (starting the root as the convention), so that would be my desire here as well.

**Comment by benmcosker** [comment]
@obuckley-kenzan / @paul-barry-kenzan 

`./dest/` as a default makes a lot of sense, as I have seen this on several Kenzan projects.  I can added this to the default for this parameter being passed in the config.  Additionally I will add the unit tests to support this new parameter.  Should a ticket be created if we go forward with this task?

**Comment by paul-barry-kenzan** [comment]
I agree that `/dest/` is a better suited default destination. 

@benmcosker re: ticket, this issue should be used as the "ticket".

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan 
Correct on process.

@benmcosker 
The contributor guidelines request that issues be used as tickets, and referenced when making a PR.  They can then be linked and provide a nice documented commit  history.
